build-and-push-docker-ci-container: build-docker-ci-container push-docker-ci-container

build-docker-ci-container:
	docker build -t kisp/ruby-chromedriver .

push-docker-ci-container:
	docker push kisp/ruby-chromedriver
