image: kisp/ruby-chromedriver

cache:
  paths:
    - vendor/bundle

before_script:
  - node -v
  - npm -v
  - npm ci
  - ruby -v
  - bundle config set --local deployment true # Install dependencies into ./vendor/bundle
  - bundle install -j $(nproc)

test:
  script:
    - make jscl-build-app >/dev/null 2>/dev/null
    - bundle exec rspec
    - env DEBUGXX=true bundle exec cucumber --color --order random --tags "not @slow"
    - env NODE_OPTIONS=--experimental-vm-modules npx jest
