# fly.toml app configuration file generated for othello-square on 2023-05-28T18:15:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "othello-square"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
