name: Release NPM

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "12.x"

    - name: Install SBCL
      run: sudo apt-get install sbcl

    - name: Build JSCL
      run: ./make.sh

    - name: Run tests
      run: ./run-tests.sh

    - name: Prepare dist directory
      run: |
        mkdir dist/
        cp jscl.html dist/index.html
        cp jscl.js jscl-web.js style.css dist/
        cp tests.html tests.js dist/
        cp jquery.js jqconsole.min.js dist/

    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_ACCESS_TOKEN }}
